name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install vsce globally
      run: npm install -g @vscode/vsce
      
    - name: Run linting
      run: npm run lint
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Package extension
      run: NODE_OPTIONS="--experimental-fetch" npx vsce package
      
    - name: List generated files
      run: ls -la *.vsix
      
    - name: Get version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: vscode-auto-commit-*.vsix
        name: Release ${{ steps.version.outputs.VERSION }}
        tag_name: v${{ steps.version.outputs.VERSION }}
        body: |
          ## Release ${{ steps.version.outputs.VERSION }}
          
          ### 安装方式
          1. 下载 `vscode-auto-commit-${{ steps.version.outputs.VERSION }}.vsix` 文件
          2. 在 VSCode 中选择 "扩展" -> "从 VSIX 安装..."
          3. 选择下载的 VSIX 文件进行安装
          
          ### 更新内容
          - 自动构建和发布
          - 支持多种 AI API
          - 智能生成 commit 消息
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
